service: ${file(serverless.config.js):repositoryName}

frameworkVersion: ^2.2.0

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-configuration
  - serverless-dynamodb-local
  - serverless-plugin-resource-tagging
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:${env:AWS_PARTITION,''}:iam::${env:AWS_ACCOUNT_ID,''}:role/${self:service}-cloudformation
  stage: ${opt:stage, "local"}
  apiKeys:
    - ${self:service}-${opt:stage, "local"}
  apiGateway:
    restApiId: ${env:AWS_REST_API_ID,''}
    restApiRootResourceId: ${env:AWS_REST_API_ROOT_RESOURCE_ID,''}
  tracing:
    lambda: true
  environment:
    SERVICE_NAME: ${self:service}
    STAGE: ${opt:stage, "local"}
  stackTags:
    ServiceName: ${self:service}
    ServiceStage: ${opt:stage, "local"}

functions:
  lambda-handler:
    role: arn:${env:AWS_PARTITION,''}:iam::${env:AWS_ACCOUNT_ID,''}:role/${self:service}-${opt:stage, "local"}
    handler: src/lambda.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: /
          method: options
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /{proxy+}
          method: options
  dynamodb-event-handler:
    role: arn:${env:AWS_PARTITION, ""}:iam::${env:AWS_ACCOUNT_ID, ""}:role/${self:service}-${opt:stage, "local"}
    handler: src/lambda.dynamoDbEventHandler
    timeout: 30
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [Table, StreamArn]
  sns-event-handler:
    role: arn:${env:AWS_PARTITION, ""}:iam::${env:AWS_ACCOUNT_ID, ""}:role/${self:service}-${opt:stage, "local"}
    handler: src/lambda.snsEventHandler
    timeout: 30
    events:
      - sns:
          topicName: ${opt:stage, "local"}-${self:service}-topic
          displayName: ${opt:stage, "local"}-${self:service}-topic

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${opt:stage, "local"}-${self:service}-table
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true
        BillingMode: PAY_PER_REQUEST

custom:
  serverless-offline:
    useChildProcesses: false
    noPrependStageInUrl: true
    prefix: ${file(serverless.config.js):serviceName}
  bundle:
    packager: yarn
    externals:
      - tsoa
      - aws-lambda
  serverless-configuration:
    local:
      del:
        - provider.apiGateway.restApiId
        - provider.apiGateway.restApiRootResourceId
  dynamodb:
    stages:
      - local
    start:
      port: 8100
      dbPath: .dynamodb
      migrate: true
